### ISSUE TITLE
getGalleryData TypeError: Cannot read property 'push' of undefined

### ISSUE THREAD

**Issue by dnm13** [H2Owater425/node-hitomi#9]
I ran a simple test with this module with several id to try.

Some ids ran fine with getGalleryData, but 1316592 did not end well.

```typescript
import { getGalleryData } from 'node-hitomi'
getGalleryData(1316592).then(console.log);
```

Error result:

```
(node:16524) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'push' of undefined
    at <anonymous>\node_modules\node-hitomi\library\index.js:1:2287
    at Array.forEach (<anonymous>)
    at <anonymous>\node_modules\node-hitomi\library\index.js:1:2241
    at Array.forEach (<anonymous>)
    at <anonymous>\node_modules\node-hitomi\library\index.js:1:2127
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:16524) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:16524) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by H2Owater425** [comment]
First of all, thanks for making issues about the error!
I'll check what makes that error happens, and fix it as fast as I can.

**Comment by dnm13** [comment]
v 1.2.0

**Comment by H2Owater425** [comment]
Okay, I just released a new version of the package and found that it works fine.
If you get any other problems while using this package. don't hesitate, make an issue like this, please!

![wow_i_fixed_it](https://user-images.githubusercontent.com/50160366/127521107-f53ea8e6-20de-476e-979d-a70b2e1da5ab.png)
